### ISSUE TITLE
Progress indicator should not be a loading bar

### ISSUE THREAD

**Issue by KenVanGilbergen** [Euroconsumers/ec-weakpasswordindicator#2]
I think initially the indicator should show a little bit of red and then move slowly into the green color if the password is getting better. I will already extract the ec-loading-bar so we can add this color option.

**Comment by kumek** [comment]
Ken, if you accept this, we can say Bernard to use weakpasswordindicator.css only. No need to inline fix as described in email. And of course after you paste it to cdn.
